### ISSUE TITLE
Alias doesn't work for lowercase English words

### ISSUE THREAD

**Issue by EdwinWang0508** [tomy0000000/Coinc#30] opened 2023-03-13 15:00 UTC
![iShot_2023-03-13_22 56 17](https://user-images.githubusercontent.com/64629689/224739994-4dbb8056-b4ca-4b9f-b7cc-b264d99ad394.gif)
As shown in the gif, the English alias cannot work properly in Coinc, but the Chinese alias can.

**Comment by tomy0000000** [comment] 2023-03-13 19:01
Just run a quick check and can confirm the bug do exists. This happens because of a wrong lowercase/uppercase transition.

For the time being, please unalias your existed alias, and add them back in ALL UPPERCASE.

I'll work on a fix in the next few days.

Thanks for reporting this issue.

**Comment by EdwinWang0508** [comment] 2023-03-15 16:56
> Just run a quick check and can confirm the bug do exists. This happens because of a wrong lowercase/uppercase transition.
> 
> For the time being, please unalias your existed alias, and add them back in ALL UPPERCASE.
> 
> I'll work on a fix in the next few days.
> 
> Thanks for reporting this issue.

im glad to help,coinc is excellent plug in alfred!

**Comment by tomy0000000** [comment] 2023-04-12 11:06
@EdwinWang0508 Sorry for the delay. I just published the fix in the latest pre-release. Can you help test if everything is working as expected?

**Comment by EdwinWang0508** [comment] 2023-04-13 05:38
> @EdwinWang0508 Sorry for the delay. I just published the fix in the latest pre-release. Can you help test if everything is working as expected?

it's my pleasure :)

**Comment by EdwinWang0508** [comment] 2023-04-13 05:46
it works perfectly!but i found another small bug.
when i choose to unalias some words,it will notice that u do unalias that words,but actually not ,it still remains in alias list.

![iShot_2023-04-13_13 42 36](https://user-images.githubusercontent.com/64629689/231664531-efa56542-666c-4f8d-99c4-e37e9f4d0493.gif)

btw,are u traveling in Bangkok？😀

**Comment by EdwinWang0508** [comment] 2023-04-13 05:52
Latest information,when I use this phrase that should have been removed,workflow shows invalid currency.I guess it could be a cache issue?

**Comment by tomy0000000** [comment] 2023-04-13 17:36
> it works perfectly!but i found another small bug. when i choose to unalias some words,it will notice that u do unalias that words,but actually not ,it still remains in alias list.

That's weird, I can't reproduce the bug in my environment. 

Here are some suggestions:

- Try opening the source directory and delete the `alias.json`, if there is one
  <img width="345" alt="CleanShot 2023-04-14 at 00 20 18@2x" src="https://user-images.githubusercontent.com/23290356/231836239-7cca357a-fbf0-421e-9450-40f6e11edfc4.png">
- Delete the `settings.json` (more details below), then remove and reinstall the workflow

If none of those work, try providing more information so I can diagnose more in-depth.

- Type `cur workflow:opendata` in Alfred, a directory should open with only one `settings.json`, and paste the content.
- [Open the Alfred Debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/) then repeat the action of the GIFs you provided, and paste the debug logs.

> btw,are u traveling in Bangkok？😀

Yep, you can DM me on any social media if you'd like to chat about it 😊

**Comment by EdwinWang0508** [comment] 2023-04-16 13:56
i try to update from alfred gallery,then it gets right!

> >Yep, you can DM me on any social media if you'd like to chat about it 😊
do u have wechat?
then i found you're taiwanese,i am chinese😁😁

**Comment by EdwinWang0508** [comment] 2023-04-16 13:59
I try to update in alfred gallery,then it goes to normal!

> Yep, you can DM me on any social media if you'd like to chat about it 😊

do you have wechat?
I just found you're taiwanese😁i am chinese too!

**Comment by tomy0000000** [comment] 2023-04-17 11:38
> do you have wechat? I just found you're taiwanese😁i am chinese too!

I have a WeChat account, but please get in touch with other social media listed on [my profile](https://github.com/tomy0000000), and we can exchange IDs or such privately.

Sorry I'm not feeling great to leave my contacts public. 😅

**Comment by tomy0000000** [comment] 2023-04-17 11:39
The bugs seem resolved, I'll close this and release the fix.

You can still comment if you have trouble contacting me. :)

**Closed as completed by tomy0000000** 2023-04-17 11:39 UTC
Labels: bug
